export { default as Main } from '../layouts/Main'
export { default as Index } from '../pages/Index'
export { default as Bio } from '../pages/Bio'
export { default as Statement } from '../pages/Statement'
export { default as Contact } from '../pages/Contact'
export { default as SignIn } from '../pages/SignIn'
export { default as Register } from '../pages/Register'
export { default as Allow } from '../pages/Allow'

export { default as AuthorForm } from '../pages/AuthorForm'
export { default as CompanyForm } from '../pages/CompanyForm'
export { default as MangaForm } from '../pages/MangaForm'
export { default as ChapterForm } from '../pages/ChapterForm'

export { default as AuthorProfile } from '../pages/AuthorProfile'
export { default as Works } from '../pages/Works'
export { default as MangaDetail } from '../pages/MangaDetail'
export { default as Page } from '../pages/Page'

export { default as MyMangas } from '../pages/MyMangas'
export { default as MangaEdit } from '../pages/MangaEdit'
export { default as ChaptersEdit } from '../pages/ChaptersEdit'
